// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxeefuuqvagnjsvuxvtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4ZWVmdXVxdmFnbmpzdnV4dnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MjI4NDEsImV4cCI6MjA1MTM5ODg0MX0.YlHm9KHr4yBTHmRNEAxnRGjRNZwF2s_zA2bK1G8Zg58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);